version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
    networks: [red-iot]

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks: [red-iot]

  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123456
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    networks: [red-iot]

  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    restart: unless-stopped
    depends_on: [influxdb, mosquitto]
    env_file: [.env]
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks: [red-iot]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on: [influxdb]
    networks: [red-iot]

  publisher1:
    build: ./publisher1
    container_name: publisher1
    restart: unless-stopped
    depends_on:
      mosquitto:
        condition: service_started
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: "1883"
      MQTT_TOPIC: tienda/visitas/telemetry
    networks: [red-iot]

  publisher2:
    build: ./publisher2
    container_name: publisher2
    restart: unless-stopped
    depends_on:
      mosquitto:
        condition: service_started
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: "1883"
      MQTT_TOPIC: tienda/operacion/telemetry
    networks: [red-iot]


  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tienda
      - POSTGRES_PASSWORD=tienda
      - POSTGRES_DB=tienda
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: [red-iot]

  webshop:
    # Construye tu app Flask desde el directorio actual.
    # Si tu Dockerfile está en la raíz de tu proyecto Flask, deja build: .
    # Si tu app está en una subcarpeta, ajusta el contexto (build: ./webshop).
    build: .
    container_name: webshop
    restart: unless-stopped
    env_file: [.env]
    depends_on: [postgres, mosquitto]
    ports:
      - "5050:5000"
    networks: [red-iot]

volumes:
  portainer_data:
  pgdata:

networks:
  red-iot:
    external: true
